server:
  port: 8080  # 服务器端口号设置


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml            # 配置mapper.xml路径
  check-config-location: true                         # 检查xml文件是否存在
  configuration:
    map-underscore-to-camel-case: true                # 开启驼峰命名法
  type-aliases-package: com.wenli.lt.entity    # 实体类存放位置


spring:
  datasource:  # 数据库配置
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8 # 数据库连接地址
    driver-class-name: com.mysql.cj.jdbc.Driver   # 数据库驱动
    username: root                                # 用户名
    password: 123456                              # 密码
